// <auto-generated />
using System;
using BLOGIC_CRM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BLOGIC_CRM.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260629145002_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BLOGIC_CRM.Models.Klient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prijmeni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RodneCislo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Vek")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Klienti");
                });

            modelBuilder.Entity("BLOGIC_CRM.Models.Poradce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prijmeni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RodneCislo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Vek")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Poradci");
                });

            modelBuilder.Entity("BLOGIC_CRM.Models.Smlouva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumPlatnosti")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumUkonceni")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumUzavreni")
                        .HasColumnType("datetime2");

                    b.Property<string>("EvidencniCislo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KlientId")
                        .HasColumnType("int");

                    b.Property<int>("SpravceSmlouvyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KlientId");

                    b.HasIndex("SpravceSmlouvyId");

                    b.ToTable("Smlouvy");
                });

            modelBuilder.Entity("BLOGIC_CRM.Models.SmlouvaPoradce", b =>
                {
                    b.Property<int>("SmlouvaId")
                        .HasColumnType("int");

                    b.Property<int>("PoradceId")
                        .HasColumnType("int");

                    b.HasKey("SmlouvaId", "PoradceId");

                    b.HasIndex("PoradceId");

                    b.ToTable("SmlouvaPoradci");
                });

            modelBuilder.Entity("BLOGIC_CRM.Models.Smlouva", b =>
                {
                    b.HasOne("BLOGIC_CRM.Models.Klient", "Klient")
                        .WithMany("Smlouvy")
                        .HasForeignKey("KlientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BLOGIC_CRM.Models.Poradce", "SpravceSmlouvy")
                        .WithMany("SpravovaneSmlouvy")
                        .HasForeignKey("SpravceSmlouvyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Klient");

                    b.Navigation("SpravceSmlouvy");
                });

            modelBuilder.Entity("BLOGIC_CRM.Models.SmlouvaPoradce", b =>
                {
                    b.HasOne("BLOGIC_CRM.Models.Poradce", "Poradce")
                        .WithMany("SmlouvaPoradce")
                        .HasForeignKey("PoradceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BLOGIC_CRM.Models.Smlouva", "Smlouva")
                        .WithMany("SmlouvaPoradce")
                        .HasForeignKey("SmlouvaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poradce");

                    b.Navigation("Smlouva");
                });

            modelBuilder.Entity("BLOGIC_CRM.Models.Klient", b =>
                {
                    b.Navigation("Smlouvy");
                });

            modelBuilder.Entity("BLOGIC_CRM.Models.Poradce", b =>
                {
                    b.Navigation("SmlouvaPoradce");

                    b.Navigation("SpravovaneSmlouvy");
                });

            modelBuilder.Entity("BLOGIC_CRM.Models.Smlouva", b =>
                {
                    b.Navigation("SmlouvaPoradce");
                });
#pragma warning restore 612, 618
        }
    }
}
